[project]
name = "manning-deep-learning-with-python-notebooks"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.13.9"
dependencies = [
    "jupyter>=1.1.1",
    "keras>=3.11.3",
    "keras-hub>=0.19.0",
    "matplotlib>=3.10.6",
    "tensorflow>=2.20.0",
]
